# Introduction

## What Is Data Science?

One widely accepted concept is the three pillars of data science:
mathematics/statistics, computer science, and domain knowledge.

## Add a Long Line

In her 2014 Presidential Address, Prof. Bin Yu, then President of the
Institute of Mathematical Statistics, gave an interesting definition:
$$
\mbox{Data Science} =
\mbox{S}\mbox{D}\mbox{C}^3,
$$
where S is Statistics, D is domain/science knowledge, and
the 3 C's are computing, collaboration/teamwork, and communication
to outsiders.

## Add a Short Line

On Linux or MacOS, just open a terminal.

### Python

Set up Python on your computer:

- Python 3.
- Python package manager __miniconda__ or __pip__.
- Integrated Development Environment (IDE) (Jupyter Notebook; RStudio; VS Code; Emacs; etc.)

Readability is important!
Check your Python coding styles against the recommended styles:
<https://peps.python.org/pep-0008/>. A good place to start if the Section on
"Code Lay-out". 

## Data Challenges

+ [ASA Data Challenge Expo](https://community.amstat.org/dataexpo/home)
+ [Kaggle](https://www.kaggle.com)
+ [DrivenData](https://www.drivendata.org)
+ [Top 10 Data Science Competitions in
  2023](https://www.knowledgehut.com/blog/data-science/data-science-competitions)
  